<a href="https://colab.research.google.com/github/SoumyoNathTripathy/ML-Project--LOAD-BOSTON/blob/main/Supervised_Learning_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#SOUMYO NATH TRIPATHY
# ML PROJECT- Load Boston 

In [ ]:
from sklearn.datasets import load_boston
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
Boston_P= load_boston()
x= Boston_P.data
y= Boston_P.target
print(x)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [ ]:
print (y)

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 3

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test= train_test_split(x,y,test_size=0.25,train_size=0.75,random_state=76)

In [ ]:
from  sklearn.preprocessing import MinMaxScaler
Sc=MinMaxScaler(feature_range=(0,1))
X_train= Sc.fit_transform(X_train)
X_test=Sc.fit_transform(X_test)
print(X_train,X_test)

[[5.14089134e-01 0.00000000e+00 6.46627566e-01 ... 8.08510638e-01
  2.17429890e-01 1.00000000e+00]
 [2.91478404e-03 0.00000000e+00 3.38343109e-01 ... 7.02127660e-01
  1.00000000e+00 3.50921986e-01]
 [6.77193849e-03 2.00000000e-01 1.28665689e-01 ... 4.25531915e-02
  9.81743496e-01 9.61702128e-02]
 ...
 [5.93926027e-02 0.00000000e+00 6.46627566e-01 ... 8.08510638e-01
  9.53040215e-01 4.83120567e-01]
 [5.81113431e-04 0.00000000e+00 4.20454545e-01 ... 8.93617021e-01
  1.00000000e+00 1.10921986e-01]
 [1.63464848e-02 0.00000000e+00 7.00879765e-01 ... 2.23404255e-01
  9.43024494e-01 0.00000000e+00]] [[0.01693877 0.         0.24119241 ... 0.88888889 0.9487367  0.51612903]
 [0.00187997 0.13888889 0.23073945 ... 0.24444444 1.         0.46274622]
 [0.00120771 0.         0.42276423 ... 0.63333333 0.96553028 0.17128176]
 ...
 [0.00621044 0.         0.16608595 ... 0.48888889 0.94765243 0.06594348]
 [0.02725324 0.         0.68408827 ... 0.18888889 0.93040496 0.02169569]
 [0.02057318 0.         0.6840

In [ ]:
y_train= y_train.reshape(-1,1)
y_train= Sc.fit_transform(y_train)
print(y_train)

[[0.04444444]
 [0.29555556]
 [1.        ]
 [0.59111111]
 [0.01333333]
 [0.32888889]
 [0.32      ]
 [0.51333333]
 [0.32      ]
 [0.05333333]
 [0.62666667]
 [0.26888889]
 [0.33333333]
 [0.55777778]
 [0.39111111]
 [0.60888889]
 [0.41333333]
 [0.62222222]
 [0.34222222]
 [0.65777778]
 [0.54222222]
 [0.61111111]
 [0.30888889]
 [0.28888889]
 [0.07777778]
 [0.        ]
 [0.19777778]
 [0.27777778]
 [0.34      ]
 [0.34      ]
 [0.22666667]
 [0.40444444]
 [0.38666667]
 [0.20222222]
 [0.62444444]
 [0.19555556]
 [0.41777778]
 [0.43111111]
 [0.35555556]
 [0.29555556]
 [0.55111111]
 [0.48888889]
 [0.55777778]
 [1.        ]
 [0.61555556]
 [0.22666667]
 [0.67555556]
 [0.20222222]
 [0.66444444]
 [0.17333333]
 [0.12      ]
 [0.82888889]
 [0.27555556]
 [0.18666667]
 [0.37555556]
 [1.        ]
 [0.37555556]
 [0.40666667]
 [0.18      ]
 [1.        ]
 [0.88444444]
 [0.66888889]
 [1.        ]
 [0.29777778]
 [0.37111111]
 [0.48      ]
 [0.19555556]
 [0.37111111]
 [1.        ]
 [0.22222222]
 [0.05555556]
 [0.30

In [ ]:
from sklearn.linear_model import LinearRegression
Linear_R= LinearRegression()
Linear_R.fit(X_train,y_train)
Predicted_values_MLR= Linear_R.predict(X_test)
print(Predicted_values_MLR)

[[ 0.14327016]
 [ 0.30728044]
 [ 0.41978008]
 [ 0.59472732]
 [ 0.55995583]
 [ 0.50190144]
 [ 0.36589015]
 [ 0.44105588]
 [ 0.51042542]
 [ 0.28706374]
 [ 0.30793721]
 [ 0.21462711]
 [ 0.15673253]
 [ 0.41721547]
 [ 0.28842011]
 [ 0.4105379 ]
 [ 0.29845638]
 [ 0.00992905]
 [ 0.35233715]
 [ 0.32190852]
 [ 0.38272493]
 [ 0.56909258]
 [ 0.34583186]
 [ 0.31709011]
 [ 0.11586898]
 [ 0.55055255]
 [ 0.49389675]
 [ 0.6678577 ]
 [ 0.34401572]
 [ 0.42020137]
 [ 0.28962115]
 [ 0.31216023]
 [ 0.41909893]
 [ 0.40040973]
 [ 0.53239415]
 [ 0.39378046]
 [ 0.36557888]
 [ 0.32975378]
 [ 0.40594942]
 [ 0.35354142]
 [ 0.1851786 ]
 [ 0.32794278]
 [ 0.75514357]
 [ 0.44754725]
 [ 0.32994569]
 [ 0.39090704]
 [ 0.23563843]
 [ 0.58132042]
 [ 0.51879347]
 [ 0.23462943]
 [ 0.43862882]
 [ 0.57665559]
 [ 0.18433729]
 [ 0.33731423]
 [ 0.29390956]
 [ 0.36601169]
 [ 0.53494292]
 [ 0.41664735]
 [ 0.35774851]
 [ 0.08359368]
 [ 0.35227116]
 [ 0.24879138]
 [ 0.41676849]
 [ 0.25454181]
 [ 0.26721567]
 [ 0.38690781]
 [ 0.42099

In [ ]:
Predicted_values_MLR= Sc.inverse_transform(Predicted_values_MLR)
print(Predicted_values_MLR)

[[11.44715732]
 [18.82761987]
 [23.89010363]
 [31.76272961]
 [30.19801252]
 [27.58556465]
 [21.46505689]
 [24.84751479]
 [27.96914381]
 [17.9178682 ]
 [18.85717423]
 [14.65822009]
 [12.05296391]
 [23.77469627]
 [17.97890485]
 [23.47420572]
 [18.43053729]
 [ 5.44680739]
 [20.85517162]
 [19.48588347]
 [22.22262166]
 [30.6091661 ]
 [20.5624339 ]
 [19.26905486]
 [10.21410416]
 [29.77486467]
 [27.2253539 ]
 [35.05359649]
 [20.48070721]
 [23.90906187]
 [18.03295166]
 [19.04721018]
 [23.85945188]
 [23.01843796]
 [28.95773689]
 [22.72012069]
 [21.45104939]
 [19.83891999]
 [23.26772399]
 [20.90936398]
 [13.33303691]
 [19.75742509]
 [38.98146084]
 [25.13962604]
 [19.84755589]
 [22.59081674]
 [15.60372955]
 [31.15941905]
 [28.34570593]
 [15.55832418]
 [24.73829691]
 [30.9495016 ]
 [13.29517809]
 [20.17914032]
 [18.22593023]
 [21.47052603]
 [29.07243127]
 [23.74913069]
 [21.09868306]
 [ 8.76171553]
 [20.85220212]
 [16.19561231]
 [23.7545821 ]
 [16.45438154]
 [17.02470504]
 [22.41085154]
 [23.94466

In [ ]:
#EVALUATION METRICES OF MLR

In [ ]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import math


In [ ]:
MAE=mean_absolute_error(y_test, Predicted_values_MLR)
print(MAE)
MSE=mean_squared_error(y_test, Predicted_values_MLR)
print(MSE)
RMSE= math.sqrt(MSE)
print(RMSE)
R2=r2_score(y_test, Predicted_values_MLR)
print(R2)

2.939433362698197
17.309236065228887
4.160437004117343
0.6988343407769659


In [ ]:
def mean_absolute_percentage_error(y_true,y_pred):
  y_true, y_pred= np.array(y_true),np.array(y_pred)
  return np.mean(np.abs((y_true-y_pred)/y_true))*100
  

In [ ]:
MAPE= mean_absolute_percentage_error(y_test, Predicted_values_MLR)
print(MAPE)

43.713152116475015


In [ ]:
#POLYNOMIAL LINEAR REGRESSION

In [ ]:
x= Boston_P.data[:, 5]
y= Boston_P.target
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test= train_test_split(x,y,test_size=0.25,train_size=0.75,random_state=76)
from sklearn.preprocessing import PolynomialFeatures
Poly_P= PolynomialFeatures(degree=2)
X_train= X_train.reshape(-1,1)
Poly_X=Poly_P.fit_transform(X_train)
from sklearn.linear_model import LinearRegression
Linear_R= LinearRegression()
Poly_L_R= Linear_R.fit(Poly_X,y_train)
X_test=X_test.reshape(-1,1)
Poly_Xt= Poly_P.fit_transform(X_test)
Predicted_values_P= Poly_L_R.predict(Poly_Xt)
print(Predicted_values_P)


[16.7207051  20.45735935 21.36404397 24.34601616 22.09863788 22.27272945
 20.07969026 18.88023333 25.70852339 18.97974164 19.77910143 16.8504308
 18.04593507 21.57970957 21.82414982 20.48809969 17.44822857 16.53960147
 18.94645026 22.37812096 19.62119028 23.94662928 20.63518217 17.41029363
 17.44822857 22.70749998 20.74468554 30.35896531 18.34945928 21.00658347
 18.46799598 17.4211078  19.19569427 19.23674147 24.434784   19.41664192
 20.41904367 20.76827493 23.35825368 20.24436225 18.53742735 20.02039489
 34.30564928 20.41904367 17.85807945 18.39292582 16.21217849 27.0141017
 25.91939473 19.09384454 22.23775504 21.39700866 15.52513263 18.45543551
 16.71596874 21.56300283 24.60353459 20.02778974 18.39915484 18.52475956
 18.72330291 16.87484432 22.31655721 24.75360289 18.63947207 25.83481205
 21.03065578 19.29174425 14.64499717 22.59994266 26.03620565 19.2504629
 25.46843351 16.86018157 26.23936019 18.51843299 16.9289833  20.25190343
 23.38629177 26.8924616  19.66402281 21.60480625 14.42

In [ ]:
from sklearn.metrics import r2_score
R2=r2_score(y_test, Predicted_values_P)
print(R2)

0.6448365947580208


In [ ]:
#Therefore Polynomial Regression had accuracy of 64%

In [ ]:
def mean_absolute_percentage_error(y_true,y_pred):
  y_true, y_pred= np.array(y_true),np.array(y_pred)
  return np.mean(np.abs((y_true-y_pred)/y_true))*100

In [ ]:
MAPE= mean_absolute_percentage_error(y_test, Predicted_values_P)
print(MAPE)

19.5047881654086


In [ ]:
#RandomForestRegressor Method:

In [ ]:
  from sklearn.ensemble import RandomForestRegressor
  Random_F=RandomForestRegressor(n_estimators=500, max_depth=20,random_state=33)
  Random_F.fit(X_train, y_train)
  Predicted_val_RF= Random_F.predict(X_test)                                                              
  #Predicted_val_RF= Predicted_val_RF.reshape(-1,1)
  #Predicted_val_RF=Sc.inverse_transform( Predicted_val_RF)
  print(Predicted_val_RF)


[19.7244     17.50432    19.67145465 27.79241667 23.61057127 21.62565194
 21.89303136 18.0064706  30.98481333 22.67732108 21.50300566 18.46242222
 17.64025971 22.23536032 12.34931603 17.6702     16.69679176 12.1154
 21.45269441 14.05745655 23.22157225 24.3206     12.50354333 17.64165714
 16.69679176 23.37629358 19.75617725 35.5387     20.31431841 23.52272196
 22.10678791 19.59099176 18.89529785 19.12257118 18.52942905 19.12011814
 21.39414    24.30920059 23.55361667 29.52495667 22.00553434 21.57778136
 36.617      21.39414    20.32436766 39.10117341 12.7396     29.9412
 27.88035    15.3922825  22.49985194 18.24777739  9.00679619 20.12450458
 19.664      22.24336032 21.15718    21.37673136 39.65643008 22.37246291
 21.23167999 24.22742222 20.75085194 16.64924    19.47333315 28.36111
 21.65472196 19.22201013 13.9564     21.64236867 19.98393    19.3402433
 26.5114     19.83522222 19.70622286 22.37246291 19.85075556 28.96215667
 23.55661667 29.5602     22.6525278  23.51254698  9.6488     45

In [ ]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import math

In [ ]:
MAE=mean_absolute_error(y_test, Predicted_val_RF)
print(MAE)
MSE=mean_squared_error(y_test, Predicted_val_RF)
print(MSE)
RMSE= math.sqrt(MSE)
print(RMSE)
R2=r2_score(y_test, Predicted_val_RF)
print(R2)

4.543688985997357
38.06519334185436
6.169699615204484
0.3376987289877703


In [ ]:
def mean_absolute_percentage_error(y_true,y_pred):
  y_true, y_pred= np.array(y_true),np.array(y_pred)
  return np.mean(np.abs((y_true-y_pred)/y_true))*100

In [ ]:
MAPE= mean_absolute_percentage_error(y_test, Predicted_val_RF)
print(MAPE)

26.842957083360155


In [ ]:
#SUPPORT VECTOR REGRESSION

In [ ]:
from sklearn.svm import SVR
Regressor_SVR= SVR(kernel='rbf')
Regressor_SVR.fit(X_train, y_train)
Predicted_values_SVR= Regressor_SVR.predict(X_test)
print(Predicted_values_SVR)


[17.35622602 20.63105269 21.32791226 24.68303077 22.00059581 22.17591519
 20.37140159 19.55434984 26.59973705 19.62658184 20.17079589 17.52506875
 18.8665032  21.51435143 21.73665342 20.65277396 18.25116212 17.11695664
 19.60258682 22.28502308 20.0659393  24.14951459 20.75823438 18.20819804
 18.25116212 22.6402262  20.83854775 32.82527126 19.13674657 21.03771277
 19.23550475 18.22049282 19.77862122 19.80691395 24.8039544  19.92920238
 20.6041221  20.85606555 23.40166679 20.48316813 19.29175017 20.33156448
 36.78686858 20.6041221  18.68549492 19.17337394 16.68472255 28.46964976
 26.90285536 19.70763762 22.1402018  21.35583645 15.91769431 19.22520643
 17.35001184 21.49958869 25.03587156 20.33652297 19.17858305 19.28157278
 19.43702346 17.55650716 22.22101724 25.24414182 19.3724158  26.78121868
 21.05656115 19.84457673 16.25731742 22.52189897 27.07088672 19.81633529
 26.2555191  17.53763942 27.36303043 19.276476   17.62578532 20.48833384
 23.43611955 28.29716764 20.09440444 21.53663042 17

In [ ]:
Predicted_values_SVR=Predicted_values_SVR.reshape(-1,1)
Predicted_values_SVR= Sc.inverse_transform(Predicted_values_SVR)
print(Predicted_values_SVR)

[[ 786.03017085]
 [ 933.39737125]
 [ 964.75605189]
 [1115.73638485]
 [ 995.02681134]
 [1002.91618364]
 [ 921.71307148]
 [ 884.94574286]
 [1201.98816721]
 [ 888.19618276]
 [ 912.68581525]
 [ 793.62809363]
 [ 853.99264412]
 [ 973.14581451]
 [ 983.14940402]
 [ 934.37482839]
 [ 826.30229541]
 [ 775.26304885]
 [ 887.11640697]
 [1007.82603842]
 [ 907.96726843]
 [1091.72815669]
 [ 939.12054721]
 [ 824.36891166]
 [ 826.30229541]
 [1023.81017919]
 [ 942.7346486 ]
 [1482.13720672]
 [ 866.15359585]
 [ 951.69707453]
 [ 870.59771363]
 [ 824.92217691]
 [ 895.03795477]
 [ 896.31112761]
 [1121.17794786]
 [ 901.81410716]
 [ 932.18549433]
 [ 943.52294968]
 [1058.07500539]
 [ 926.74256568]
 [ 873.12875776]
 [ 919.92040143]
 [1660.40908611]
 [ 932.18549433]
 [ 845.84727156]
 [ 867.80182709]
 [ 755.81251483]
 [1286.13423934]
 [1215.6284914 ]
 [ 891.84369308]
 [1001.30908087]
 [ 966.01264038]
 [ 721.29624373]
 [ 870.13428931]
 [ 785.75053291]
 [ 972.48149119]
 [1131.61422004]
 [ 920.14353381]
 [ 868.0362372

In [ ]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import math

In [ ]:
MAE=mean_absolute_error(y_test, Predicted_values_SVR)
print(MAE)
MSE=mean_squared_error(y_test, Predicted_values_SVR)
print(MSE)
RMSE= math.sqrt(MSE)
print(RMSE)
R2=r2_score(y_test, Predicted_values_SVR)
print(R2)

3.2935146337740577
22.028696428136886
4.693473812448183
0.6167198334690795


In [ ]:
def mean_absolute_percentage_error(y_true,y_pred):
  y_true, y_pred= np.array(y_true),np.array(y_pred)
  return np.mean(np.abs((y_true-y_pred)/y_true))*100

In [ ]:
MAPE= mean_absolute_percentage_error(y_test, Predicted_values_SVR)
print(MAPE)

20.24876297379519
